load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "inventory_lib",
    srcs = ["main.go"],
    importpath = "github.com/EvalOps/keep/services/inventory",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/logging",
        "//services/inventory/server",
    ],
)

go_binary(
    name = "inventory",
    embed = [":inventory_lib"],
    visibility = ["//visibility:public"],
)
