load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "mfa_lib",
    srcs = ["main.go"],
    importpath = "github.com/EvalOps/keep/cmd/mfa",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/logging",
        "//services/mfa",
    ],
)

go_binary(
    name = "mfa",
    embed = [":mfa_lib"],
    visibility = ["//visibility:public"],
)
