load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "secrets",
    srcs = [
        "azure.go",
        "helper.go",
        "secrets.go",
        "ssm.go",
        "vault.go",
    ],
    importpath = "github.com/EvalOps/keep/pkg/secrets",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/logging",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_config//:config",
        "@com_github_aws_aws_sdk_go_v2_service_ssm//:ssm",
        "@com_github_azure_azure_sdk_for_go_sdk_azcore//:azcore",
        "@com_github_azure_azure_sdk_for_go_sdk_azidentity//:azidentity",
        "@com_github_azure_azure_sdk_for_go_sdk_security_keyvault_azsecrets//:azsecrets",
        "@com_github_hashicorp_vault_api//:api",
    ],
)
